// <auto-generated />
namespace FILM_RFID_READER_DEPLOY.Properties {
    using System;
    using System.Drawing;
    using System.Resources;
    using System.Globalization;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        private static ResourceManager resourceMan;
        private static CultureInfo resourceCulture;
        internal Resources() {}
        internal static ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("FILM_RFID_READER_DEPLOY.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        internal static CultureInfo Culture {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }
        internal static Bitmap ounq1mw5kdxy {
            get { return ((Bitmap)(ResourceManager.GetObject("ounq1mw5kdxy", resourceCulture))); }
        }
    }
}
