<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>FILM_RFID_READER_DEPLOY</RootNamespace>
    <AssemblyName>FILM_RFID_READER_DEPLOY</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Configuration" />
    <Reference Include="Symbol.RFID3.Host">
      <HintPath>Symbol.RFID3.Host.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Library.Database\Library.Database.csproj" />
    <ProjectReference Include="..\Library.Reader\Library.Reader.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="App.config" />
    <Content Include="Resources\ounq1mw5kdxy.gif" />
  </ItemGroup>
</Project>